import type { Metadata } from "next";
import "../styles/global.css";
import RootLayoutComponent from "@/components/layouts/root-layout";

export const metadata: Metadata = {
  title: "OTW TL",
  description: "Generated by create next app",
  icons: "https://otw-tl.com/static/logo1.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <RootLayoutComponent>{children}</RootLayoutComponent>;
}
